### ISSUE TITLE
qb-drawtext  and translations 

### ISSUE THREAD

**Issue by Andyauk** [Ademo93/qb-territories#2]
you might need to change to english. 
Vous êtes entré sur le territoire d'un gang - You entered gang territory
Vous avez quitté le territoire d'un gang - You left gang territory
                       
and qb-drawtext error when you go in and out of the zone.

**Comment by Ademo93** [comment]
Yes i will soon create a locale folder with eng/fr

**Comment by Ademo93** [comment]
Translation should be working now
